const jobTitles = [
    "Accountant",
    "Actor",
    "Acupuncturist",
    "Administrative assistant",
    "Advertising executive",
    "Aerospace engineer",
    "Air traffic controller",
    "Aircraft mechanic",
    "Anesthesiologist",
    "Animal trainer",
    "Anthropologist",
    "App developer",
    "Archaeologist",
    "Architect",
    "Art director",
    "Artist",
    "Astronomer",
    "Audiologist",
    "Auto mechanic",
    "Babysitter",
    "Baker",
    "Barber",
    "Bartender",
    "Biologist",
    "Blogger",
    "Bookkeeper",
    "Botanist",
    "Bricklayer",
    "Bus driver",
    "Business analyst",
    "Butcher",
    "Call center representative",
    "Camera operator",
    "Carpenter",
    "Cashier",
    "Chef",
    "Chemist",
    "Childcare worker",
    "Chiropractor",
    "Civil engineer",
    "Cleaner",
    "Coach",
    "Comedian",
    "Computer programmer",
    "Concierge",
    "Construction worker",
    "Content writer",
    "Cook",
    "Copywriter",
    "Cosmetologist",
    "Counselor",
    "Courier",
    "Court reporter",
    "Dancer",
    "Data analyst",
    "Database administrator",
    "Dental hygienist",
    "Dentist",
    "Dermatologist",
    "Designer",
    "Detective",
    "Dietitian",
    "Digital marketer",
    "Director",
    "Disc jockey (DJ)",
    "Dog groomer",
    "Dog walker",
    "Economist",
    "Editor",
    "Electrician",
    "Engineer",
    "Environmental scientist",
    "Event planner",
    "Executive assistant",
    "Farmer",
    "Fashion designer",
    "Film director",
    "Financial advisor",
    "Firefighter",
    "Fitness instructor",
    "Flight attendant",
    "Florist",
    "Food scientist",
    "Forensic scientist",
    "Fundraiser",
    "Game developer",
    "Gardener",
    "Geologist",
    "Graphic designer",
    "Hairdresser",
    "Handyman",
    "Health inspector",
    "Historian",
    "Home inspector",
    "Hotel manager",
    "Housekeeper",
    "Human resources manager",
    "Illustrator",
    "Industrial engineer",
    "Information security analyst",
    "Insurance agent",
    "Interior designer",
    "Interpreter",
    "Investigator",
    "IT consultant",
    "Janitor",
    "Jeweler",
    "Journalist",
    "Judge",
    "Kindergarten teacher",
    "Landscaper",
    "Lawyer",
    "Librarian",
    "Lifeguard",
    "Linguist",
    "Locksmith",
    "Makeup artist",
    "Management consultant",
    "Market researcher",
    "Marketing manager",
    "Massage therapist",
    "Mathematician",
    "Mechanic",
    "Medical assistant",
    "Medical coder",
    "Medical laboratory technician",
    "Medical secretary",
    "Meteorologist",
    "Microbiologist",
    "Model",
    "Music producer",
    "Music teacher",
    "Nail technician",
    "Nanny",
    "Network administrator",
    "Neurologist",
    "News anchor",
    "Nurse",
    "Nutritionist",
    "Occupational therapist",
    "Office manager",
    "Optician",
    "Optometrist",
    "Painter",
    "Paralegal",
    "Paramedic",
    "Pediatrician",
    "Personal assistant",
    "Personal trainer",
    "Pharmacist",
    "Photographer",
    "Physical therapist",
    "Physician",
    "Physicist",
    "Pilot",
    "Plumber",
    "Police officer",
    "Political scientist",
    "Preschool teacher",
    "Principal",
    "Producer",
    "Professor",
    "Programmer",
    "Project manager",
    "Psychiatrist",
    "Psychologist",
    "Public relations specialist",
    "Quality control inspector",
    "Radiologist",
    "Receptionist",
    "Recruitment specialist",
    "Registered nurse",
    "Research assistant",
    "Restaurant manager",
    "Sales representative",
    "Scientist",
    "Security guard",
    "Server",
    "Social media manager",
    "Social worker",
    "Software developer",
    "Speech therapist",
    "Statistician",
    "Stockbroker",
    "Surgeon",
    "Surveyor",
    "Systems analyst",
    "Tax preparer",
    "Teacher",
    "Technical writer",
    "Technician",
    "Therapist",
    "Tour guide",
    "Translator",
    "Travel agent",
    "Truck driver",
    "Tutor",
    "TV producer",
    "UI/UX designer",
    "Underwriter",
    "Urologist",
    "Veterinarian",
    "Video editor",
    "Waiter/Waitress",
    "Web designer",
    "Welder",
    "Writer",
    "X-ray technician",
    "Yoga instructor",
    "Zookeeper",
    "Zoologist"
  ];

export default jobTitles